package bzha2709.comp5216.sydney.edu.au.bloodpressuremonitor.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import bzha2709.comp5216.sydney.edu.au.bloodpressuremonitor.bean.Measure;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEASURE".
*/
public class MeasureDao extends AbstractDao<Measure, Void> {

    public static final String TABLENAME = "MEASURE";

    /**
     * Properties of entity Measure.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Time = new Property(0, java.util.Date.class, "time", false, "TIME");
        public final static Property Dia = new Property(1, short.class, "dia", false, "DIA");
        public final static Property Sys = new Property(2, short.class, "sys", false, "SYS");
        public final static Property Pulse = new Property(3, short.class, "pulse", false, "PULSE");
        public final static Property Position = new Property(4, short.class, "position", false, "POSITION");
        public final static Property Arm = new Property(5, short.class, "arm", false, "ARM");
        public final static Property Mood = new Property(6, short.class, "mood", false, "MOOD");
    }


    public MeasureDao(DaoConfig config) {
        super(config);
    }
    
    public MeasureDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEASURE\" (" + //
                "\"TIME\" INTEGER," + // 0: time
                "\"DIA\" INTEGER NOT NULL ," + // 1: dia
                "\"SYS\" INTEGER NOT NULL ," + // 2: sys
                "\"PULSE\" INTEGER NOT NULL ," + // 3: pulse
                "\"POSITION\" INTEGER NOT NULL ," + // 4: position
                "\"ARM\" INTEGER NOT NULL ," + // 5: arm
                "\"MOOD\" INTEGER NOT NULL );"); // 6: mood
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_MEASURE_TIME ON \"MEASURE\"" +
                " (\"TIME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEASURE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Measure entity) {
        stmt.clearBindings();
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(1, time.getTime());
        }
        stmt.bindLong(2, entity.getDia());
        stmt.bindLong(3, entity.getSys());
        stmt.bindLong(4, entity.getPulse());
        stmt.bindLong(5, entity.getPosition());
        stmt.bindLong(6, entity.getArm());
        stmt.bindLong(7, entity.getMood());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Measure entity) {
        stmt.clearBindings();
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(1, time.getTime());
        }
        stmt.bindLong(2, entity.getDia());
        stmt.bindLong(3, entity.getSys());
        stmt.bindLong(4, entity.getPulse());
        stmt.bindLong(5, entity.getPosition());
        stmt.bindLong(6, entity.getArm());
        stmt.bindLong(7, entity.getMood());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Measure readEntity(Cursor cursor, int offset) {
        Measure entity = new Measure( //
            cursor.isNull(offset + 0) ? null : new java.util.Date(cursor.getLong(offset + 0)), // time
            cursor.getShort(offset + 1), // dia
            cursor.getShort(offset + 2), // sys
            cursor.getShort(offset + 3), // pulse
            cursor.getShort(offset + 4), // position
            cursor.getShort(offset + 5), // arm
            cursor.getShort(offset + 6) // mood
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Measure entity, int offset) {
        entity.setTime(cursor.isNull(offset + 0) ? null : new java.util.Date(cursor.getLong(offset + 0)));
        entity.setDia(cursor.getShort(offset + 1));
        entity.setSys(cursor.getShort(offset + 2));
        entity.setPulse(cursor.getShort(offset + 3));
        entity.setPosition(cursor.getShort(offset + 4));
        entity.setArm(cursor.getShort(offset + 5));
        entity.setMood(cursor.getShort(offset + 6));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Measure entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Measure entity) {
        return null;
    }

    @Override
    public boolean hasKey(Measure entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
