package bzha2709.comp5216.sydney.edu.au.bloodpressuremonitor.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import bzha2709.comp5216.sydney.edu.au.bloodpressuremonitor.bean.User_Score;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER__SCORE".
*/
public class User_ScoreDao extends AbstractDao<User_Score, Void> {

    public static final String TABLENAME = "USER__SCORE";

    /**
     * Properties of entity User_Score.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Time = new Property(0, java.util.Date.class, "time", false, "TIME");
        public final static Property Score = new Property(1, double.class, "score", false, "SCORE");
    }


    public User_ScoreDao(DaoConfig config) {
        super(config);
    }
    
    public User_ScoreDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER__SCORE\" (" + //
                "\"TIME\" INTEGER," + // 0: time
                "\"SCORE\" REAL NOT NULL );"); // 1: score
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_USER__SCORE_TIME ON \"USER__SCORE\"" +
                " (\"TIME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER__SCORE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User_Score entity) {
        stmt.clearBindings();
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(1, time.getTime());
        }
        stmt.bindDouble(2, entity.getScore());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User_Score entity) {
        stmt.clearBindings();
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(1, time.getTime());
        }
        stmt.bindDouble(2, entity.getScore());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public User_Score readEntity(Cursor cursor, int offset) {
        User_Score entity = new User_Score( //
            cursor.isNull(offset + 0) ? null : new java.util.Date(cursor.getLong(offset + 0)), // time
            cursor.getDouble(offset + 1) // score
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User_Score entity, int offset) {
        entity.setTime(cursor.isNull(offset + 0) ? null : new java.util.Date(cursor.getLong(offset + 0)));
        entity.setScore(cursor.getDouble(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(User_Score entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(User_Score entity) {
        return null;
    }

    @Override
    public boolean hasKey(User_Score entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
